name: Delete prereleases related to deleted branch
on:
  pull_request:
    types: [closed]

jobs:
  delete_release:
    runs-on: ubuntu-latest
    steps:
    - name: Delete non-master branch release
      uses: author/action-rollback@1.0.0
      with:
        tag: draft-assets-for-${{ github.event.pull_request.head.ref }}
        always_delete_tag: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
